version: "3"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5430:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - postgres:/data
volumes:
  postgres:
